[package]
name = "libp2p-tls"
edition = "2018"
description = "TLS encryption protocol for libp2p"
version = "0.1.0"
authors = ["Grant Wuerker <gwuerker@gmail.com>"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
futures = "0.1"
libp2p-core = { version = "0.8.0", path = "../../core" }
rw-stream-sink = { version = "0.1.1", path = "../../misc/rw-stream-sink" }
tokio-io = "0.1.0"
bytes = "0.4"
log = "0.4.6"
openssl = "0.10"
rand = "0.6"
quinn-proto = "0.2"
simple_asn1 = "0.3"
webpki = "0.19"
tokio-threadpool = "0.1"
rustls = { version = "0.15", features = ["dangerous_configuration"] }
tokio-rustls = "0.10.0-alpha.3"
